### ISSUE TITLE
TaskbarSystemMonitor.exe --memory

### ISSUE THREAD

**Issue by drandreaskrueger** [mikecann/Windows7-Taskbar-Monitor#1]
Grrreat!
I have been using it for a year now. It tells me when my system gets close to being in danger. Since I have put the paging file to a fixed 2000 MB, my computer runs much more stable, and responsive - but I have to keep an eye on the RAM. And your tool is really helpful for that. Thanks a lot.

There is one feature request. I have tried 

```
TaskbarSystemMonitor.exe /?  
TaskbarSystemMonitor.exe --help  
TaskbarSystemMonitor.exe /help  
```

but I cannot get a list of commandline switches. 

Right now, it comes up with CPU selected. So with each start, I have to manually click "MEMORY" once. Which is not too bad really, that's why I never took the time to write to you. But today's the day :-) 

I would like to start it with MEMORY on as default, e.g.

```
TaskbarSystemMonitor.exe --memory
```

Perhaps in a next update?

Thanks a million for considering this.

**Comment by mikecann** [comment]
Hi!

Wow its so good to hear that someone else uses this on a daily basis! I
love it and keep meaning to do improvements for it. Perhaps when windows 10
finally implements an API for progress bars than ill make the jump.

As for your question, I think I mentioned this on my blog a little while
ago but I really should put it in the readme, you are right, but you can do
it like this:

TaskbarSystemMonitor.exe -type cpu

or

TaskbarSystemMonitor.exe -type mem

or

TaskbarSystemMonitor.exe -type net

I like to put all three in my startup folder so they just bootup and work
when I start the computer.

I hope that helps!

Mike

On 2 March 2016 at 02:31, drandreaskrueger notifications@github.com wrote:

> Grrreat!
> I have been using it for a year now. It tells me when my system gets close
> to being in danger. Since I have put the paging file to a fixed 2000 MB, my
> computer runs much more stable, and responsive - but I have to keep an eye
> on the RAM. And your tool is really helpful for that. Thanks a lot.
> 
> There is one feature request. I have tried
> 
> TaskbarSystemMonitor.exe /?
> TaskbarSystemMonitor.exe --help
> TaskbarSystemMonitor.exe /help
> 
> but I cannot get a list of commandline switches.
> 
> Right now, it comes up with CPU selected. So with each start, I have to
> manually click "MEMORY" once. Which is not too bad really, that's why I
> never took the time to write to you. But today's the day :-)
> 
> I would like to start it with MEMORY on as default, e.g.
> 
> TaskbarSystemMonitor.exe --memory
> 
> Perhaps in a next update?
> 
> Thanks a million for considering this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mikecann/Windows7-Taskbar-Monitor/issues/1.

## 

_Mike Cann_
http://www.mikecann.co.uk/
@mikeysee http://www.twitter.com/mikeysee

**Comment by drandreaskrueger** [comment]
>  its so good to hear that someone else uses this ...

Yes, I know. Have had that several times in my life. Thinking no reaction means no usage/reading/perception. And then getting positively surprised by a user/reader/someone-who-actually-notices-the-amount-and-quality-of-our-altruistic-production :-) 

I guess we have to actively and visibly ask for feedback if we want feedback.

**Comment by drandreaskrueger** [comment]
> I really should put it in the readme

There is no readme.txt in my v0.4 folder. There are only Windows7.DesktopIntegration.dll, VistaBridgeLibrary.dll, TaskbarSystemMonitor.exe

Yes, a readme. Good idea. Place one there, right beside the executables.

**Comment by drandreaskrueger** [comment]
Another thing to consider is 

```
TaskbarSystemMonitor.exe /?  
TaskbarSystemMonitor.exe --help  
TaskbarSystemMonitor.exe /help  
```

because **that** is _the first thing that I have tried_. And careful: On Windows I would probably not even try a 

```
TaskbarSystemMonitor.exe -help  
```

with a single dash.

**Comment by drandreaskrueger** [comment]
As an eternal reminder for myself, I have now put three files into that folder

```
TaskbarSystemMonitor.exe -type cpu.bat
TaskbarSystemMonitor.exe -type mem.bat
TaskbarSystemMonitor.exe -type net.bat
```

with these contents

```
set MYPATH=%~dp0
start %MYPATH%TaskbarSystemMonitor.exe -type cpu
```

and

```
set MYPATH=%~dp0
start %MYPATH%TaskbarSystemMonitor.exe -type mem
```

and

```
set MYPATH=%~dp0
start %MYPATH%TaskbarSystemMonitor.exe -type net
```

I think to include those 3 *.bat files is the easiest-to-understand way, especially for newbies.

**Comment by drandreaskrueger** [comment]
and finally I changed the call in Windows\Start Menu\All Programs\Startup -  
AND NOW IT IS STARTING UP WITH MEM, YIEHAH :-) 

Thanks!

**Comment by mikecann** [comment]
Oh sorry I meant the readme.md on this github page (https://github.com/mikecann/Windows7-Taskbar-Monitor) but you are quite right there should be both a readme.txt and some --help or /? command args to tell you what the options are. 

Ill make a note to add those when I get a sec. Thanks a bunch!

**Comment by drandreaskrueger** [comment]
Idea: Why then not also include a 

```
TaskbarSystemMonitor.exe --help.bat
```

file with this content:

```
@echo OFF
echo .
set MYPATH=%~dp0
start %MYPATH%TaskbarSystemMonitor.exe --help
echo .
pause
```

that shows all the commandline options. 

But anyways, all my problems are solved!
Enjoy your life! 
:-)

**Comment by mikecann** [comment]
Cool, good idea! Ill make a note to look into that soon :)

On 4 March 2016 at 23:17, drandreaskrueger notifications@github.com wrote:

> Idea: Why then not also include a
> 
> TaskbarSystemMonitor.exe --help.bat
> 
> file with this content:
> 
> @echo OFF
> echo .
> set MYPATH=%~dp0
> start %MYPATH%TaskbarSystemMonitor.exe --help
> echo .
> pause
> 
> that shows all the commandline options.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mikecann/Windows7-Taskbar-Monitor/issues/1#issuecomment-192318132
> .

## 

_Mike Cann_
http://www.mikecann.co.uk/
@mikeysee http://www.twitter.com/mikeysee
